### ISSUE TITLE
archimateviewer.nl

### ISSUE THREAD

**Issue by 12345swo** [guidohajanssen/archimateviewer#4]
Hi.  This might be just an issue with the [site](http://www.archimateviewer.nl) I've tried both .archimate and the xml open exchange files for the Skeleton example that comes with Archi (v 3.2.2) and I get this error ...

```
starting upload.Moving /tmp/phpjOIjH3 to /home/guidoql183/domains/archimateviewer.nl/public_html/archimate/models/phpjOIjH3
The file /home/guidoql183/domains/archimateviewer.nl/public_html/archimate/models/phpjOIjH3 has been uploaded.
./publishopengroup.sh /home/guidoql183/domains/archimateviewer.nl/public_html/archimate/models/phpjOIjH3 site &> stderroutput:string(0) "" return code:126unsuccesful generation
```

**Comment by guidohajanssen** [comment]
Fixed. It had to do with the permission of the publishopengroup.sh script. It was not executable.

**Comment by guidohajanssen** [comment]
Thanks for exploring the viewer. And thanks for pointing out the problem. I
fixed it.

2016-09-09 16:27 GMT+02:00 12345swo notifications@github.com:
