### ISSUE TITLE
403 forbidden for www.archimateviewer.nl

### ISSUE THREAD

**Issue by AAtley** [guidohajanssen/archimateviewer#5]
Hi, Is there a problem with the online viewer? When I visit http://www.archimateviewer.nl/ I get a 403 Forbidden response.

**Comment by guidohajanssen** [comment]
Hi,

Thanks for exploring the archimate viewer and for informing me about the
problems. It should be working again now.

Guido Janssen

2016-09-10 11:55 GMT+02:00 Adrian-A notifications@github.com:
